<?php
namespace AppBundle\Repository;
/**
 * articuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class articuloRepository extends \Doctrine\ORM\EntityRepository
{
    //a) Muestra todos los artículos de un pedido según la id del pedido
    public function queryArticulosByPedido($id)
    {
        return $this->createQueryBuilder('a')
            ->select('a.id', 'a.nombre', 'a.precio')
            ->leftJoin('a.pedidos', 'pedido')
            ->andWhere('pedido.id = :id')
            ->setParameter('id', $id)
            ->addOrderBy('a.createdAt', 'DESC')
            ->getQuery();
    }

    public function ArticulosByPedido($id)
    {
        return $this->queryArticulosByPedido($id)->execute();
    }


}