<?php
namespace AppBundle\Repository;
/**
 * clienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class clienteRepository extends \Doctrine\ORM\EntityRepository
{
    //a) Selecciona todos los clientes que tengan un pedido de valor superior a 30€
    public function supTreinta()
    {
        return $this->createQueryBuilder('cliente')
            ->select('cliente.nombre', 'pedido.precio')
            ->leftJoin('cliente.pedidos', 'pedido')
            ->addOrderBy('pedido.createdAt', 'DESC')
            ->andWhere('pedido.precio>30')
            ->getQuery()
            ->execute()
            ;
    }
}

