<?php
namespace AppBundle\Repository;
/**
 * pedidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pedidoRepository extends \Doctrine\ORM\EntityRepository
{
    //a) Muestra todos los pedidos de un cliente según su id
    public function queryPedidoByCliente($id)
    {
        return $this->createQueryBuilder('p')
            ->select('cliente.nombre', 'p.id', 'p.createdAt', 'p.precio' )
            ->leftJoin('p.cliente', 'cliente')
            ->andWhere('cliente.id = :id')
            ->setParameter('id', $id)
            ->addOrderBy('p.createdAt', 'DESC')
            ->getQuery();
    }
    public function PedidoByCliente($id)
    {
        return $this->queryPedidoByCliente($id)->execute();
    }
}
